In [1]:
import pandas as pd

In [2]:
lab_output = pd.read_csv('/media/data/huyennm/mimic-iv/notebook/lab/lab_results/lab_output.csv')
lab_output

,subject_id,stay_id,hematocrit_min,hematocrit_max,hemoglobin_min,hemoglobin_max,platelets_min,platelets_max,wbc_min,wbc_max,...,ast_min,ast_max,ck_min,ck_max,ck_mb_min,ck_mb_max,ntprobnp_min,ntprobnp_max,troponin_t_min,troponin_t_max
0,13180007,30000213,23.9,27.6,7.4,8.5,219.0,243.0,5.7,7.7,...,19.0,24.0,NaN,NaN,NaN,NaN,944.0,944.0,0.03,0.03
1,18421337,30000484,24.6,31.0,8.1,9.9,357.0,403.0,24.2,30.1,...,44.0,50.0,40.0,74.0,NaN,NaN,6239.0,6239.0,0.16,0.23
2,15726459,30000831,38.0,40.8,12.4,13.3,285.0,311.0,14.2,21.3,...,50.0,57.0,NaN,NaN,2.0,3.0,NaN,NaN,4.33,4.64
3,12168737,30001336,24.3,26.4,8.2,8.9,162.0,163.0,8.1,9.0,...,36.0,38.0,NaN,NaN,2.0,2.0,4844.0,4844.0,1.60,1.65
4,14311522,30002548,35.2,39.7,11.6,13.0,132.0,148.0,8.7,15.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25777,19046950,39998622,40.5,45.9,13.3,14.5,202.0,252.0,7.5,19.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25778,15954569,39998871,24.1,26.0,7.0,7.8,235.0,303.0,6.8,15.0,...,11.0,15.0,25.0,41.0,3.0,3.0,NaN,NaN,0.05,0.15
25779,19425920,39999168,26.5,27.6,7.9,8.1,231.0,246.0,13.6,15.2,...,80.0,80.0,403.0,403.0,8.0,10.0,NaN,NaN,0.14,0.16
25780,15669140,39999172,18.9,23.1,6.1,7.0,176.0,193.0,5.3,5.5,...,40.0,40.0,22.0,23.0,NaN,NaN,NaN,NaN,0.01,0.01
25781,15498623,39999384,23.4,24.8,7.7,8.0,159.0,176.0,10.3,10.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
len(lab_output.columns)

46

In [7]:
missing_percentage = (lab_output.isna().sum() / len(lab_output)) * 100
missing_percentage

subject_id          0.000000
stay_id             0.000000
hematocrit_min      0.694283
hematocrit_max      0.694283
hemoglobin_min      0.733070
hemoglobin_max      0.733070
platelets_min       0.752463
platelets_max       0.752463
wbc_min             0.756342
wbc_max             0.756342
rbc_min             0.767978
rbc_max             0.767978
creatinine_min      0.581801
creatinine_max      0.581801
bun_min             0.597316
bun_max             0.597316
lactate_min       100.000000
lactate_max       100.000000
glucose_min         0.872702
glucose_max         0.872702
sodium_min          0.643860
sodium_max          0.643860
potassium_min       0.659375
potassium_max       0.659375
calcium_min         5.542627
calcium_max         5.542627
magnesium_min       2.525017
magnesium_max       2.525017
chloride_min        0.624467
chloride_max        0.624467
inr_min             8.269335
inr_max             8.269335
pt_min              8.261578
pt_max              8.261578
alt_min            41.490187
alt_max            41.490187
ast_min            40.807540
ast_max            40.807540
ck_min             62.590179
ck_max             62.590179
ck_mb_min          58.218912
ck_mb_max          58.218912
ntprobnp_min       79.439144
ntprobnp_max       79.439144
troponin_t_min     57.334575
troponin_t_max     57.334575
dtype: float64